name: GitHub Metrics

on:
  schedule: # اجرا به صورت زمان‌بندی‌شده
    - cron: "0 */12 * * *"
  workflow_dispatch: # اجرا دستی

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: hossein-shnyvry
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Tehran
